"use strict";

const cocktails = {
  "moscow mule": ["vodka", "ginger beer", "lime", "2/.5/6"],
  cosmopolitan: ["vodka", "cranberry", "lime", "cointreau", "1.5/1/.5/.5"],
  "vodka cranberry": ["vodka", "cranberry", "2/6"],
  "lemon drop": ["vodka", "cointreau", "lemon", "simple syrup", "2/.5/1/1"],
  "long island": [
    "vodka",
    "tequila",
    "gin",
    "rum",
    "sour mix",
    "coke",
    ".75/2",
  ],
  AMF: [
    "vodka",
    "tequila",
    "gin",
    "rum",
    "blue curacao",
    "coke",
    "sour mix",
    ".5/2",
  ],

  "gin and tonic": ["gin", "lime", "tonic", "cucumber", "2/.5/4"],
  "tom collins": ["gin", "lemon", "simple syrup", "soda", "2/1/.5"],
  gimlet: ["gin", "lime", "simple syrup", "2/.5/.5"],
  bramble: ["gin", "lemon", "creme de mure", "simple syrup", "2/1/.5/.5"],
  "gin fizz": ["gin", "lemon", "simple syrup", "egg white", "soda", "2/1/.75"],
  "french 75": ["gin", "lemon", "simple syrup", "champagne", "1/.5/.5/3"],
  "south side": ["gin", "lime", "simple syrup", "mint", "2/1/1"],
  "gin mule": ["gin", "lime", "ginger beer", "2/.5/6"],
  negroni: ["gin", "aperol", "vermouth", "1/all"],
  martini: ["gin", "vermouth", "2/1"],
  "corpse reviver 2": ["gin", "lillet", "lemon", "vermouth", ".75/all"],

  margaritas: ["tequila", "cointreau", "lime", "2/1/1"],
  "mexican coke": ["tequila", "lime", "coke", "2/.5/6"],
  "tequila mule": ["tequila", "lime", "ginger beer", "2/.5/6"],
  "oaxaca old fashioned": [
    "tequila",
    "mezcal",
    "simple syrup",
    "bitters",
    "1.5/.5/.25",
  ],

  daiquiri: ["rum", "lime", "simple syrup", "2/1/.75"],
  mojito: ["rum", "lime", "simple syrup", "mint", "soda", "2/.75/.5"],
  "dark and stormy": ["rum", "lime", "ginger beer", "2/.5/6"],
  "cuba libre": ["rum", "lime", "coke", "2/.5/6"],
  "old cuban": [
    "rum",
    "simple syrup",
    "lime",
    "champagne",
    "mint",
    "1.5/1/.75/2",
  ],

  "old fashioned": [
    "bourbon",
    "simple syrup",
    "bitters",
    "orange peel",
    "2/.25",
  ],
  "paper plane": [
    "bourbon",
    "aperol",
    "lemon",
    "amaro Nonino Quintessentia",
    ".75/all",
  ],
  "mint julep": ["bourbon", "simple syrup", "mint", "ice", "2/.25"],
  manhattan: ["bourbon, vermouth", "bitters", "2/1"],
  boulevardier: ["bourbon", "aperol", "vermouth", "1.25/1/1"],

  penicillin: [
    "scotch",
    "lemon",
    "honey-ginger syrup",
    "islay scotch",
    "2/.75/.75/.25",
  ],
  "blood and sand": [
    "scotch",
    "cherry liquor",
    "vermouth",
    "orange",
    ".75/all",
  ],

  "whiskey sour": [
    "whiskey",
    "lemon",
    "simple syrup",
    "egg white",
    "bitters",
    "2/1/.75",
  ],
  "new york sour": [
    "whiskey",
    "lemon",
    "simple syrup",
    "egg white",
    "red wine",
    "2/1/.75/.5",
  ],
  "toki highball": ["japanese", "whiskey", "soda", "lemon peel", "2/6"],
  "irish mule": ["irish", "whiskey", "lime", "ginger beer", "2/.5/6"],
  "green tea": [
    "irish",
    "whiskey",
    "sour mix",
    "peach schnapps",
    "1.5/.75/.75",
  ],
  "old pal": ["rye", "aperol", "vermouth", "lemon peel", "1/all"],
  sidecar: ["cognac", "cointreau", "lemon", "1.5/.75/.75"],
  "grand mouth": ["grand marnier", "vermouth", "lemon", "2/.75/.75"],
};
